### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by romanrm** [bitcoin/secp256k1#172]
# ./autogen.sh 
Makefile.am:3: Libtool library used but `LIBTOOL' is undefined
Makefile.am:3:   The usual way to define `LIBTOOL' is to add `LT_INIT'
Makefile.am:3:   to `configure.ac' and run `aclocal' and `autoconf' again.
Makefile.am:3:   If `LT_INIT' is in `configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

Any idea?

**Comment by geeknik** [comment]
I'm seeing this issue when trying to compile Bitcoin on Debian 7 and I have libtool 2.4.2-1.1 installed.

geeknik@deb7fuzz:~$ which libtool
/usr/bin/libtool

geeknik@deb7fuzz:~$ whereis libtool
libtool: /usr/bin/libtool /usr/bin/X11/libtool /usr/share/libtool /usr/share/man/man1/libtool.1.gz

So now what?
