### ISSUE TITLE
Suggestion to add secp256k1_ec_pubkey_compress() function

### ISSUE THREAD

**Issue by ufasoft** [bitcoin/secp256k1#259]
The library has secp256k1_ec_pubkey_decompress()
But symmetric operation _compress() does not exist.

It is possible to export PrivKey to compressed PubKey form, but sometime PrivKey is not available.

As I see the implementation is very simple: copy first 33 bytes and OR some bitmask.

**Comment by sipa** [comment]
Yes the reasoning for not having such a function is because it is trivial.

However as the library is growing more into a fully-featured API rather
than a collection of low-level routines, I think it makes sense to add it.

**Comment by apoelstra** [comment]
Recommend close since the `pubkey_t` API now means that keys don't have a un/compressedness until the time of serialization.

**Comment by ufasoft** [comment]
agree
