### ISSUE TITLE
./tests program doesn't print out a clear "success" or "failure" message.

### ISSUE THREAD

**Issue by mlmikael** [bitcoin/secp256k1#281]
~/secp256k1$ ./tests
test count = 64
random seed = c8cf1c09fc87faabb2607ee1d4928a8e
random run = 99368fd45ee84e517f745d3302d37bd4

The ./tests program doesn't indicate tests success (or failure for that sake) so clearly. Would you mind adding printf("test was successful.\n"); / printf("test failed.\n"); lines?

**Comment by gmaxwell** [comment]
Sorry for the delayed response here,  the tests return their status in the return code (and failures result in big messages). Automation should be using the return code.

Can you help me understand what requirement is driving this request?

**Comment by mlmikael** [comment]
I guess with https://github.com/bitcoin/secp256k1/pull/295 it's resolved;

I just founds its console output confusing, and I didn't see any clear mention in the code that the result would be passed through the return code - I guess by this it's resolved and we can close this issue.
