### ISSUE TITLE
check that travis builds what we think it builds

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/secp256k1#311]
right now "32bit scalar + recovery" is actually building:

configure: Using assembly optimizations: x86_64
configure: Using field implementation: 64bit
configure: Using bignum implementation: gmp
configure: Using scalar implementation: 32bit
configure: Using endomorphism optimizations: no
configure: Building ECDH module: no
configure: Building Schnorr signatures module: 
configure: Building ECDSA pubkey recovery module: no

**Comment by sipa** [comment]
ouch
