### ISSUE TITLE
Decompressing public key

### ISSUE THREAD

**Issue by h0vhannes** [bitcoin/secp256k1#330]
Hi,
I have a compressed secp256k1 public key and need to decompress it in javascript. I found that it can be done through https://github.com/wanderer/secp256k1-node package.

That package has `decompressPublickey` function which uses `secp256k1_ec_pubkey_decompress` from this (secp256k1) lib. But `secp256k1_ec_pubkey_decompress` was removed in the following commit https://github.com/bitcoin/secp256k1/commit/23cfa914d2d17dfc3d28ae3b10d95385dac5d835#diff-0d77700fa6e05639431c962ffaa5365aL285
so node's lib, which basically wraps C library misses that function, actually the function in lib is equal to undefined.

After all, I just want to decompress a compressed public key in node to encrypt a message with ECIES encryption having just a compressed key.

What should I do in this situation?

Thanks in advance, Hovhannes.

**Comment by DavidEGrayson** [comment]
You might compile and install the last version of libsecp256k1 that has that function.  Alternatively, work on updating the secp256k1-node project.

Please note that this project is in an experimental stage and the developers don't really want people trusting it too much.  But there will eventually be a stable release with a version number that would be more appropriate to use.

**Comment by h0vhannes** [comment]
Thanks, David.

I've checked the current version, and it lacks compress/decompress functions. So if I'm not mistaken you suggest to use older version?

**Comment by sipa** [comment]
There is no more need for compress/decompress functions. You can just use the pubkey_parse + pubkey_serialize function.

I don't understand why you need decompression for ECIES, though.

**Comment by h0vhannes** [comment]
Thank you, Pieter.

I saw that compress/decompress were replaced with `secp256k1_ec_pubkey_serialize`, but I don't know how to exactly use it for decompressing. In that case I can slightly modify node library to use `secp256k1_ec_pubkey`. Could you please give a usage example ?

this is the link to the secp256k1 wrapper code in node lib for reference
https://github.com/wanderer/secp256k1-node/blob/master/functions.cc

**Comment by sipa** [comment]
Read the documentation (the header file) :)

**Comment by h0vhannes** [comment]
Ok, let me look through it

Regarding the decompression. I use https://github.com/bitchan/eccrypto to encrypt messages and it works only with decompressed 65 byte keys, but I have only 33 byte key, so I need to convert it to the decompressed version.

Thanks, once again. Hovhannes.

**Comment by h0vhannes** [comment]
This is the solution if someone is interested

var elliptic = require('elliptic');
var ec = new elliptic.ec('secp256k1');
var publicKeyUncompressed = ec.keyFromPublic(PublicKeyCompressed, 'hex').getPublic(false, 'hex');

**Comment by apoelstra** [comment]
If `require('elliptic')` means to use the node.js elliptic library, this is bad advice in general because that library is badly non-constant time. (Though in this specific case timing does not matter.)

It is trivial to convert between compressed and non-compressed serialization with our library. You parse and reserialize.

But this is not a support board, and libsecp256k1 is not in a released state. Please do not treat it like one.

**Comment by h0vhannes** [comment]
Thanks, @apoelstra!
