### ISSUE TITLE
Why have any heap memory allocation?

### ISSUE THREAD

**Issue by netanelkl** [bitcoin/secp256k1#355]
Take a look:
https://github.com/bitcoin/secp256k1/blob/master/src/secp256k1.c#L61

Shouldn't the caller provide a  secp256k1_context. This way you let the calling app manage its memory as it wants.

**Comment by sipa** [comment]
That would mean exposing the secp256k1_context type, so new versions
couldn't change its contents anymore. Furthermore, there are a few more
allocations done for the precomputed tables in a context.

**Comment by netanelkl** [comment]
Makes sense. 
It's only on creation so shouldn't be a problem for embedded systems that have to be more deterministic.
Then again, those systems will likely be able to link to a known version, anyway...
Thanks!
