### ISSUE TITLE
secp256k1_ec_pubkey_serialize+secp256k1_ec_pubkey_parse fails for some keys

### ISSUE THREAD

**Issue by kristofferkoch** [bitcoin/secp256k1#380]
Hi. I have a concrete issue where I store a pubkey with secp256k1_ec_pubkey_serialize, but then when I try to load the pubkey again, it fails.

Most privkeys work, but approx 1/5 fails.

Am I missing something in the documentation, or is this a bug?

```
$ cat test-case.c 
#include <stdio.h>
#include <stdlib.h>
#include <secp256k1.h>
#include <stdint.h>

static const uint8_t PRIVKEY[32] = {0xa1, 0xc0, 0x25, 0xdc, 0x31, 0x70, 0x97, 0xbe,
                                    0xa3, 0xcf, 0xbd, 0x25, 0xe1, 0xd3, 0x95, 0x21,
                                    0x60, 0x1e, 0x54, 0x99, 0x95, 0x01, 0x62, 0x70,
                                    0xa6, 0x45, 0x7a, 0x73, 0x9c, 0x1e, 0x20, 0x16};

int main(int argc, char **argv) {
  secp256k1_context* ctx = secp256k1_context_create(SECP256K1_CONTEXT_SIGN);

  if (secp256k1_ec_seckey_verify(ctx, PRIVKEY) == 0) {
    fprintf(stderr, "Invalid secret key\n");
    exit(1);
  }
  
  secp256k1_pubkey pubkey;
  int ret = secp256k1_ec_pubkey_create(ctx, &pubkey, PRIVKEY);
  if (ret == 0) {
    fprintf(stderr, "Invalid secret key 2\n");
    exit(1);
  }
  uint8_t pubkey_serialized[33];
  size_t pubkeylen = sizeof(pubkey);
  secp256k1_ec_pubkey_serialize(ctx, pubkey_serialized, &pubkeylen, &pubkey, SECP256K1_EC_COMPRESSED);

  secp256k1_pubkey pubkey2;
  if (secp256k1_ec_pubkey_parse(ctx, &pubkey2, pubkey_serialized, 33) == 0) {
    printf("error re-parsing public key!\n");
    exit(1);
  }
  
  secp256k1_context_destroy(ctx);
  return 0;
}
$ cc -l secp256k1 test-case.c -o test-case && ./test-case
error re-parsing public key!
```

**Comment by paveljanik** [comment]
Can you please print `secp256k1_ec_pubkey_parse` return value?

Your example works here...

**Comment by kristofferkoch** [comment]
How strange. Return value is 0. `secp256k1_ec_pubkey_serialize` returns 1, btw.

**Comment by paveljanik** [comment]
`secp256k1_ec_pubkey_serialize `:
*  Returns: 1 always.

**Comment by kristofferkoch** [comment]
It fails on a debian machine on yourserver.se. All other tests succeed on that machine.

This test-case succeeds on my mac. I'll try it on a different linux machine tomorrow.

**Comment by kristofferkoch** [comment]
pubkey_serialized is
`03 9d e3 1a fa 38 70 ad 5d 87 83 b9 bf ec 78 14 f7 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`
on my linux machine, and
`03 9d e3 1a fa 38 70 ad 5d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`
on my mac

Compiling with "-m32" on linux yields a key of
`03 9d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

It seems strange to me that so many zeros are present in the compressed key. Not much entropy left.

**Comment by paveljanik** [comment]
Trying it on Bitcore playground (https://bitcore.io/playground/#/units):

```
>> var priv = new bitcore.PrivateKey('a1c025dc317097bea3cfbd25e1d39521601e549995016270a6457a739c1e2016', 'livenet');
<PrivateKey: a1c025dc317097bea3cfbd25e1d39521601e549995016270a6457a739c1e2016, network: livenet>
>> var publicKey = priv.toPublicKey();
<PublicKey: 039de31afa3870ad5d8783b9bfec7814f751b45eae635973005b29c73e4f69e399>
>> 
```

Your problem is probably here:

```c
  uint8_t pubkey_serialized[33];
```

Try to change to 65.

**Comment by paveljanik** [comment]
No, your real problem is this:
```c
size_t pubkeylen = sizeof(pubkey);
```

but `pubkey` is `secp256k1_pubkey`. You should use `pubkey_serialized` instead...

**Comment by kristofferkoch** [comment]
How silly. Thank you for looking at this, and sorry for not solving my own bugs :)
