### ISSUE TITLE
Npm install fails at secp256k1

### ISSUE THREAD

**Issue by heiho1** [bitcoin/secp256k1#385]
I'm trying to install solc as per 

https://www.npmjs.com/package/solc

I have geth running locally installed via brew on os x but the npm install fails with the below output.

Some system info:

"""
| => npm -v
3.8.1
________________________________________________________________________________
| ~/Desktop/dev/ether/ComicCollector/contracts @ foamfollower (heiho1) 
| => uname -a
Darwin foamfollower 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
"""

The stacktrace:

"""
| => npm install solc > node.out
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Library/Frameworks/Python.framework/Versions/3.4/python -c import platform; print(platform.python_version());
gyp ERR! stack /Library/Frameworks/Python.framework/Versions/3.4/python: /Library/Frameworks/Python.framework/Versions/3.4/python: cannot execute binary file
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:202:12)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:475:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/heiho1/node_modules/secp256k1
gyp ERR! node -v v5.8.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rebuild"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.0.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.0.1 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/heiho1/node_modules/secp256k1/npm-debug.log
npm WARN install:secp256k1@3.0.1 secp256k1@3.0.1 install: `npm run rebuild`
npm WARN install:secp256k1@3.0.1 Exit status 1
npm WARN enoent ENOENT: no such file or directory, open '/Users/heiho1/package.json'
npm WARN heiho1 No description
npm WARN heiho1 No repository field.
npm WARN heiho1 No README data
npm WARN heiho1 No license field.
"""

**Comment by afk11** [comment]
That package isn't connected with this repository, besides them depending on this code. This seems to be the repository with the node bindings: https://github.com/wanderer/secp256k1-node they might be able to help!

**Comment by heiho1** [comment]
Thanks, I will try the -node variant.

**Comment by paveljanik** [comment]
Please close this issue.
